### ISSUE TITLE
Remove Slack Channel dependency from oauth server

### ISSUE THREAD

**Issue by chintans** [Promact/oauth-server#290]
oauth server's only responsibility is to authenticate user and provide project related details via api. Slack channel integration should not be part of the oauth server. right now we associate a project with a slack channel in oauth server. this should be done at ERP project.

**Comment by juliepromact** [comment]
## **At Present the flow is roughly described below :**

- In [OAuth](https://github.com/Promact/oauth-server)
A project is registered along the with the corresponding slack channel name.

- In [Erp](https://github.com/Promact/slack-erp-custom-integration-mvc)
When a scrum meeting is to be conducted, project details of the slack channel are required.In order to fetch the project details from [OAuth](https://github.com/Promact/oauth-server), slack channel names are compared.

This flow has to be changed as dependency of Slack Channel has to be removed from [OAuth](https://github.com/Promact/oauth-server).

## **New Flow**

### Flow 1

Create a view in [Erp](https://github.com/Promact/slack-erp-custom-integration-mvc) which lists all projects from [OAuth](https://github.com/Promact/oauth-server) and all channels of Slack from [Erp](https://github.com/Promact/slack-erp-custom-integration-mvc) .
Administrator has to link the Projects of [OAuth](https://github.com/Promact/oauth-server) to the Slack channels(1-1 relation).
A Slack Channel can be assigned to only one Project of [OAuth](https://github.com/Promact/oauth-server) and vice versa.
This set up cannot be edited or deleted.
The ProjectId would be saved in SlackChannelDetails table in [Erp](https://github.com/Promact/slack-erp-custom-integration-mvc)

**OR**

### Flow 2

Add a new command for scrum bot. "Add Project ProjectName".
When any scrum bot command is encountered in the slack channel if corresponding [OAuth](https://github.com/Promact/oauth-server)  is not found then scrum bot will reply "Please link slack channel with OAuth Project using commad "Add Project ProjectName(Name of project in OAuth server)"".
The ProjectName will be checked against the Projects table of [OAuth](https://github.com/Promact/oauth-server) and the Id of the project in [OAuth](https://github.com/Promact/oauth-server) with the given name(ProjectName) will be returned to [Erp](https://github.com/Promact/slack-erp-custom-integration-mvc) and added to SlackChannelDetails table of [Erp](https://github.com/Promact/slack-erp-custom-integration-mvc).
This is a one time set up.


@chintans Please suggest which flow is better.

**Comment by chintans** [comment]
I think Flow 2 would be better option. It would be better if we can create a new command called link, unlink, and list

https://github.com/Promact/slack-erp-custom-integration-mvc/issues/241
